config/routes.rb
Rails.application.routes.draw do
  resources :bests
  resources :converts
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#index'
end

app/models/convert.rb
class Convert < ApplicationRecord
end

app/controllers/converts_controller.rb
require "FMoney.rb"

class ConvertsController < ApplicationController
  before_action :set_convert, only: [:show, :edit, :update, :destroy]

  # GET /converts
  # GET /converts.json
  def index
    @targets = []
    @rate

    @products = Product.all
    @source = nil
    if params[:option].nil?
     @option = "EUR"
    else
     @option = params[:option]
    end
    if params[:option1].nil?
     @option1 = "EUR"
    else
     @option1 = params[:option1]
    end
    if params[:amount].nil?
     @amount = 1 
    else
     @amount = params[:amount].to_i
    end

    calculate_convert()

    if params[:mail].nil?
    else
     ExampleMailer.sample_email2('kwang180@gmail.com',@option,@opition1,@rate,@amount).deliver
    end
  end

  # GET /converts/1
  # GET /converts/1.json
  def show
  end

  # GET /converts/new
  def new
    @convert = Convert.new
  end

  # GET /converts/1/edit
  def edit
  end

  # POST /converts
  # POST /converts.json
  def create
    @convert = Convert.new(convert_params)

    respond_to do |format|
      if @convert.save
        format.html { redirect_to @convert, notice: 'Convert was successfully created.' }
        format.json { render :show, status: :created, location: @convert }
      else
        format.html { render :new }
        format.json { render json: @convert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /converts/1
  # PATCH/PUT /converts/1.json
  def update
    respond_to do |format|
      if @convert.update(convert_params)
        format.html { redirect_to @convert, notice: 'Convert was successfully updated.' }
        format.json { render :show, status: :ok, location: @convert }
      else
        format.html { render :edit }
        format.json { render json: @convert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /converts/1
  # DELETE /converts/1.json
  def destroy
    @convert.destroy
    respond_to do |format|
      format.html { redirect_to converts_url, notice: 'Convert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_convert
      @convert = Convert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def convert_params
      params.require(:convert).permit(:name, :price)
    end
    def calculate_convert()
      money = FMoney.new(@option)
      @rate = money.convert(@option1,@amount)
    end
end

app/helpers/converts_helper.rb
module ConvertsHelper
end

app/views/converts/_form.html.erb
<%= form_for(convert) do |f| %>
  <% if convert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(convert.errors.count, "error") %> prohibited this convert from being saved:</h2>

      <ul>
      <% convert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/converts/edit.html.erb
<h1>Editing Convert</h1>

<%= render 'form', convert: @convert %>

<%= link_to 'Show', @convert %> |
<%= link_to 'Back', converts_path %>

app/views/converts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
   <div class="large-12 columns">

     <center style="padding: 18px 15px 3px 15px;border: 1px solid #e6e6e6;background-color: #ffffff;border-bottom: 0;1">
       <h4>Convert exchange rate</h4>
     </center>
     <div class="callout columns" style="border: 1px solid #e6e6e6;">
        <%= form_for products_path, :method => 'get' do %>
          <legend>Select source country</legend>
          <%= select_tag(:option, options_for_select([["Euroup","EUR"],["South Korea","KRW"],["North Korea","KPW"]], params[:option] ), class:"select") %>
          <legend>Select target country</legend>
          <%= select_tag(:option1, options_for_select([["Euroup","EUR"],["South Korea","KRW"],["North Korea","KPW"]], params[:option] ), class:"select") %>
          <%= text_field_tag :amount, params[:amount] , type: "amount", name: "amount", class: "input-group-field large-12 columns", placeholder: "Insert amount "%>
          </br>
          <label for="checkbox1">
            <%= check_box_tag :mail, true %>send mail
          </lable>
          <%= submit_tag "Get exchange rate", :id => ['option','option1'], class: "button expand large-12 large-centered columns"%>
        <% end %>
     </div>
     <center style="padding: 18px 15px 3px 15px;border: 1px solid #e6e6e6;background-color: #ffffff;border-bottom: 0;1">
       <h4>Result convert rate from <%= @option %></h4>
     </center>
     <div class="callout" style="border: 1px solid #e6e6e6;">
       <p> 
           <%= @option1 %>&nbsp;&nbsp<%= @rate %> </br> 
       </p>
     </div>
<!--
     <h1>Products</h1>
     
     <table>
       <thead>
         <tr>
           <th>Name</th>
           <th>Price</th>
           <th colspan="3"></th>
         </tr>
       </thead>
     
       <tbody>
         <% @products.each do |product| %>
           <tr>
             <td><%= product.name %></td>
             <td><%= product.price %></td>
             <td><%= link_to 'Show', product %></td>
             <td><%= link_to 'Edit', edit_product_path(product) %></td>
             <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
           </tr>
         <% end %>
       </tbody>
     </table>
     
     <br>
     
     <%= link_to 'New Product', new_product_path %>

  </div>
</div>
-->

app/views/converts/new.html.erb
<h1>New Convert</h1>

<%= render 'form', convert: @convert %>

<%= link_to 'Back', converts_path %>

app/views/converts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @convert.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @convert.price %>
</p>

<%= link_to 'Edit', edit_convert_path(@convert) %> |
<%= link_to 'Back', converts_path %>