config/routes.rb
Rails.application.routes.draw do
  resources :bests
  resources :converts
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#index'
end

app/models/best.rb
class Best < ApplicationRecord
end

app/controllers/bests_controller.rb
require "FMoney.rb"

class BestsController < ApplicationController
  before_action :set_best, only: [:show, :edit, :update, :destroy]

  # GET /bests
  # GET /bests.json
  def index
    @targets = []
    @rate

    @products = Product.all
    @source = nil
    if params[:option].nil?
     @option = "EUR"
    else
     @option = params[:option]
    end
    if params[:option1].nil?
     @option1 = "EUR"
    else
     @option1 = params[:option1]
    end

    calculate_best()

    if params[:mail].nil?
    else
     ExampleMailer.sample_email1('kwang180@gmail.com',@option,@option1,@rate).deliver
    end
  end

  # GET /bests/1
  # GET /bests/1.json
  def show
  end

  # GET /bests/new
  def new
    @best = Best.new
  end

  # GET /bests/1/edit
  def edit
  end

  # POST /bests
  # POST /bests.json
  def create
    @best = Best.new(best_params)

    respond_to do |format|
      if @best.save
        format.html { redirect_to @best, notice: 'Best was successfully created.' }
        format.json { render :show, status: :created, location: @best }
      else
        format.html { render :new }
        format.json { render json: @best.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bests/1
  # PATCH/PUT /bests/1.json
  def update
    respond_to do |format|
      if @best.update(best_params)
        format.html { redirect_to @best, notice: 'Best was successfully updated.' }
        format.json { render :show, status: :ok, location: @best }
      else
        format.html { render :edit }
        format.json { render json: @best.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bests/1
  # DELETE /bests/1.json
  def destroy
    @best.destroy
    respond_to do |format|
      format.html { redirect_to bests_url, notice: 'Best was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_best
      @best = Best.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def best_params
      params.require(:best).permit(:name, :price)
    end

    def calculate_best()
      money = FMoney.new(@option)
      @rate = money.best(@option1)
    end
end

app/helpers/bests_helper.rb
module BestsHelper
end

app/views/bests/_form.html.erb
<%= form_for(best) do |f| %>
  <% if best.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(best.errors.count, "error") %> prohibited this best from being saved:</h2>

      <ul>
      <% best.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bests/edit.html.erb
<h1>Editing Best</h1>

<%= render 'form', best: @best %>

<%= link_to 'Show', @best %> |
<%= link_to 'Back', bests_path %>

app/views/bests/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
   <div class="large-12 columns">

     <center style="padding: 18px 15px 3px 15px;border: 1px solid #e6e6e6;background-color: #ffffff;border-bottom: 0;1">
       <h4>Best exchange rate</h4>
     </center>
     <div class="callout columns" style="border: 1px solid #e6e6e6;">
        <%= form_for products_path, :method => 'get' do %>
          <legend>Select source country</legend>
          <%= select_tag(:option, options_for_select([["Euroup","EUR"],["South Korea","KRW"],["North Korea","KPW"]], params[:option] ), class:"select") %>
          <%= select_tag(:option1, options_for_select([["Euroup","EUR"],["South Korea","KRW"],["North Korea","KPW"]], params[:option] ), class:"select") %>

          <label for="checkbox1">
            <%= check_box_tag :mail, true %>send mail
          </lable>
          <%= submit_tag "Get exchange rate", :id => ['option','option1'], class: "button expand large-12 large-centered columns"%>
        <% end %>
     </div>
     <br>
     <center style="padding: 18px 15px 3px 15px;border: 1px solid #e6e6e6;background-color: #ffffff;border-bottom: 0;1">
       <h4>Result rate from <%= @option %></h4>
     </center>
     <div class="callout" style="border: 1px solid #e6e6e6;">
       <p> 
           <%= @option1 %>&nbsp;&nbsp<%= @rate %> </br> 
       </p>
     </div>
<!--
     <h1>Products</h1>
     
     <table>
       <thead>
         <tr>
           <th>Name</th>
           <th>Price</th>
           <th colspan="3"></th>
         </tr>
       </thead>
     
       <tbody>
         <% @products.each do |product| %>
           <tr>
             <td><%= product.name %></td>
             <td><%= product.price %></td>
             <td><%= link_to 'Show', product %></td>
             <td><%= link_to 'Edit', edit_product_path(product) %></td>
             <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
           </tr>
         <% end %>
       </tbody>
     </table>
     
     <br>
     
     <%= link_to 'New Product', new_product_path %>

  </div>
</div>
-->

app/views/bests/new.html.erb
<h1>New Best</h1>

<%= render 'form', best: @best %>

<%= link_to 'Back', bests_path %>

app/views/bests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @best.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @best.price %>
</p>

<%= link_to 'Edit', edit_best_path(@best) %> |
<%= link_to 'Back', bests_path %>